# Generated by Django 5.2.6 on 2025-10-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja')], default='Disponible', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('qr_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
    ]
