# Generated by Django 5.2.7 on 2025-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_compromiso', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('Vencido', 'Vencido')], default='Abierto', max_length=20)),
            ],
        ),
    ]
