# Generated by Django 5.0.6 on 2025-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='registradoPor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
