# Generated by Django 5.0.6 on 2025-11-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_prestamo_registradopor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='registradoPor_id',
            new_name='registrado_por_id',
        ),
    ]
